services:
  - type: web
    name: assignment-eval-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: GEMINI_API_KEY
        sync: false
